
import Header from "./Header"
import Provider from "./Provider"
import { getServerSession } from 'next-auth/next'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession;
  return (
    <html lang="en">
      
      <body>
        
        <Provider session={session}>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
